---
title       : DRINKING WATER INCIDENTS 
subtitle    : THE REGULATOR'S PERSPECTIVE
author      : 
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## INTRODUCTION    
- State Government introduced new legislation for regulating recycled and drinking water quality
- The Act 2008 aims to further strengthen the safety and reliability of water supplies.     
- In recognition of the impacts of the Act on the drinking water industry, implementation of the requirements is occurring in two stages. 
- Stage 1 commenced in January 2009 and required drinking water service providers to:
    - monitor water quality in their drinking water schemes
    - report all drinking water incidents to OWSR
    - submit drinking water quality reports on a quarterly basis, summarising their water quality monitoring results

--- 

## Range of Drinking Water Schemes

-  Currently there are 384 drinking water schemes, owned by 84 registered providers across the state.
-  These service populations ranging from two to greater than 100,000.
-  A range of water sources are currently used including artesian bores, groundwater, surface water and desalinated sea water.

---   

## Drinking Water Quality Incidents

- The Notice issued to providers in December 2008 requires them to report the following drinking water incidents:
    - detection of Escherichia coli (E. coli).
    - detection of a pathogen.
    - detection of a chemical parameter that does not meet a health guideline value in the Guideline.
    - detection of radioactivity exceeding gross alpha or gross beta screening values in the Guideline.
    - detection of a parameter for which there is no guideline value.
    - an event or series of events likely to affect drinking water quality or will cause difficulty 
      in the ability to adequately treat or provide drinking water.     

---
## Conclusion

- In summary, the standard of drinking water services is highly variable around the state. 
It appears that regulation of drinking water providers needs to be further
supplemented by a range of support actions to achieve desired outcomes in relation to
drinking water quality. Drinking water regulation is achieving improvement in water
quality through a greater focus on drinking water quality management.  



